channels:
    - pytorch
    - nvidia
    - conda-forge
name:
    tukra
dependencies:
    - affogato
    - zarr
    - z5py
    - nifty
    - torch-em
    - imageio
    - python-elf
    - pytorch>=2.0
    - pytorch-cuda>=11.8  # you may need to update the pytorch version to match your system
    - tensorboard
    - torchvision
    - kornia
    - pip:
        - cellpose